# SPDX-License-Identifier: MIT
# Copyright (C) 2021 Roland Csaszar
#
# Project:  TzolkinWaves
# File:     create_packages.yml
#
################################################################################

name: Nuget Packages

on:
  release:
    types: [created]

  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv

      - name: Setup MkDocs
        run: |
          cd $GITHUB_WORKSPACE
          python -m pipenv install --dev

      - name: Setup Tools
        run: |
          dotnet tool restore
          dotnet paket restore

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"

      - name: Build Package
        run: |
          cd $GITHUB_WORKSPACE
          dotnet fake run ./build.fsx target Packages $GIT_TAG_NAME

      - name: Generate Changelog
        run: |
          cd $GITHUB_WORKSPACE/scripts
          ./get_changelog.sh > ../first_changelog.md

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Version ${{ env.GIT_TAG_NAME }}
          body_path: first_changelog.md
          files: ./nuget/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Release NuGet to GitHub
      #  uses: svenstaro/upload-release-action@v2
      #  if: startsWith(github.ref, 'refs/tags/')
      #  with:
      #    release_name: Version ${{ env.GIT_TAG_NAME }}
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    tag: ${{ github.ref }}
      #    file_glob: false
      #    asset_name: NuGet Package
      #    file: ./packages/TzolkinWaves.nupkg

      - name: Upload
        run: |
          cd $GITHUB_WORKSPACE
          dotnet nuget push ./nuget/*.nupkg -k ${{ secrets.NUGET_PACKAGE }} -s https://api.nuget.org/v3/index.json

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Nuget Packages
          path: ./nuget/*
